### ISSUE TITLE
Improve CLA

### ISSUE THREAD

**Issue by DeclanChidlow** [revoltchat/cla#1]
### What do you want to see?

Improve contributor license agreement in regard to community concerns outlined here:
https://wiki.revolt.chat/en/transparency/inquiries/2023-12-02-vale-regarding-revolt

**Comment by DeclanChidlow** [comment]
There are fears that the CLA allows for Revolt to adopt a closed source license in future.

**Comment by DeclanChidlow** [comment]
There are fears that rights are given completely to a single person.

**Comment by DeclanChidlow** [comment]
The CLA is wordy and difficult to digest, which can lead to contributors feeling confused.

**Comment by lo2dev** [comment]
There are two reasons the CLA exists:
1. The 2 components under the CLA will become closed source at some point or at the very least they plan to;
2. Selling contributor code to corporate entities under proprietary licenses which is not a moral thing to do at all;

I think a CLA which restricts relicensing is in conflict with the 2 reasons. That's why I fight for the removal of the CLA and not some alternative. I think the GPL without a CLA does a good job of preventing closed source relicensing.

But at last I will provide an alternative: https://drewdevault.com/2021/04/12/DCO.html

**Comment by lo2dev** [comment]
And to repost from the dev chat, any CLA with a relicense clause with prevent and block contributions from me to the components affected.

**Comment by DarkRTA** [comment]
A CLA would pretty much stop me from ever contributing outright as I don't wan't any of my code to be used without it also being under an open source license.

That being said if we must have a CLA we need some sort of way to ensure future versions of the software as used by Revolt will always be available under an open source license. I really dont want any potential for a rug pull like with redis.

**Comment by DeclanChidlow** [comment]
Current discussion is about moving to a Fiduciary Licence Agreement (FLA). This would replace the CLA and be more permissive.

KDE current employ this to great success. https://en.wikipedia.org/wiki/Contributor_License_Agreement#KDE

**Comment by insertish** [comment]
CLA requirement has been dropped.
For the time being, a DCO will be required (commit sign-off), and later as an alternative, opt-in will be available into an FLA.
